version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 795602562705.dkr.ecr.us-east-2.amazonaws.com
      - docker login --username AWS -p $(aws ecr get-login-password --region us-east-2) 473626464363.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:latest 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:latest
      # - docker tag 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:latest 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:$IMAGE_TAG
  post_build:
    commands: 
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:latest
      # - docker push 795602562705.dkr.ecr.us-east-2.amazonaws.com/django-nginx:latest
      - echo Writing image definitions file...
      - printf '[{"name":"django-nginx","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
