# Generated by Django 4.1.1 on 2022-09-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('website', models.URLField(null=True)),
                ('categories', models.CharField(max_length=400, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('tag', models.CharField(max_length=400)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('reviews', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('address', models.TextField(null=True)),
                ('review_link', models.URLField(null=True)),
                ('cid', models.CharField(max_length=30, unique=True)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.day')),
            ],
        ),
    ]
